manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect

    - name: samyfrancelet
      url-base: git@github.com:SamyFrancelet

  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: nrfconnect
      revision: v2.9.0
      import:
        name-blocklist:
          - matter
          - nrf-802154
          - openthread
          - cmock
          - unity
          - cddl-gen
          - homekit
          - loramac-node
          - lz4
          - lvgl
          - mipi-sys-t
          
    - name: vlad-dts
      remote: samyfrancelet
      repo-path: vlad-dts
      revision: main
      
  self:
    path: app
